# Generated by Django 3.2 on 2025-11-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('result', models.CharField(max_length=10)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_logs',
            },
        ),
    ]
